language: java

jdk:
  - oraclejdk7

# http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

#env:
#  - JVM_OPTS="-Xmx512m -XX:MaxPermSize=256m" MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m"

#before_script:
#  - "export JAVA_OPTS=\"-Xmx512m -XX:MaxPermSize=256m\""
#  - "export JVM_OPTS=\"-Xmx512m -XX:MaxPermSize=256m\""
#  - "export MAVEN_OPTS=\"-Xmx512m -XX:MaxPermSize=256m\""

script: "mvn test -B -P travis-tests"

notifications:
  email:
    on_success: always
    on_failure: always
